config/routes.rb
Rails.application.routes.draw do

  resources :categories, only: [:index, :show] do
    resources :articles, only: [:index, :new, :create, :show]
  end

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  resource :index, only: [:index]
  root to: "index#index"

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articles
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  before_action :ensure_current_user, only: [:create, :update, :destroy]

  def current_user
    user = User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def ensure_current_user
    redirect_to new_session_path unless current_user
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
    @category = Category.where(id: params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.create(article_params)
  end

  def show
    @article = Article.find_by(id: params[:id])
  end

  private

  def article_params
    params.require(:article).permit(:name)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find_by(id: params[:id])
  end

end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_current_user

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash.notice = 'Welcome back'
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_current_user

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Thanks for registering"
      session[:user_id] = @user.id
      redirect_to '/categories'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.erb
<h1><%=@category.name%></h1>
<% @articles.each do |article| %>

<li><%= link_to article.name, category_articles_path %></li>

<%end%>

<h3><%= link_to 'Submit an Article', new_category_article_path %></h3>

app/views/articles/new.html.erb
<h2>Submit something awesome</h2>
<%= form_for :article, :html => {:id => "article-form"} do |f| %>
  <%= f.label :name %>
  <%= f.text_area :name %>

  <%= f.submit 'Submit', class: 'button'%>
  <% end %>

app/views/articles/show.html.erb
<h1><%=@article.name%></h1>
<li><%=article.text%></li>
<li><%=article.link%></li>

app/views/categories/index.html.erb
<h1>Things we ♥ </h1>
<% @categories.each do |category| %>

<li><%= link_to category.name, category_articles_path(category) %></li>

<%end%>

app/views/index/index.html.erb
<div id = "index-design">

<h1 id = "index-header">discuss & discover</h1>

<%= link_to 'Sign up', new_user_path, id: 'sign-up-button' %>

</div>

<h2 id = "index-subheader">ABOUT DISCLY</h2>
<div id = "index-body">
<p>discly is your space to speak and listen about what you love. We foster discovery and discussion within and between communities of passionate individuals who care deeply about their interests.</p>
<p>Start a discussion in one of our <%= link_to 'categories', categories_path%>, or dare to explore something new.</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>discly -- discuss and discover</title>
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Satisfy">
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= stylesheet_link_tag    'normalize', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <nav>
  <%= link_to "discly", root_path, id: 'header' %>
  <%= link_to 'CATEGORIES', categories_path%>
    <div class="welcome-bar, right">
      <% if current_user %>
         Welcome <%= current_user.username %>
         <%= link_to 'Log out', session_path, method: :delete%>
      <% else %>
         <%= link_to 'Log in', new_session_path%>
      <% end %>
    </div>
  </nav>
</header>

<%= yield %>

<footer>
<p class= "right"> © 2016 Discly </p>
</footer>
</body>
</html>

app/views/users/new.html.erb
<%= form_for @user do |f| %>

  <h2>Register</h2>
  <div>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div>
    <%= f.label :confirm_password %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

<% if @user.errors.any? %>
  <div class="error_report">
    <% @user.errors.full_messages.each do |msg| %>
      <%= msg %>
    <% end %>
  </div>
<% end %>